// <auto-generated />
namespace WeddingPlanner.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addnewpropertytovenue : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addnewpropertytovenue));
        
        string IMigrationMetadata.Id
        {
            get { return "202001201431464_add new property to venue"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
