namespace WeddingPlanner.Migrations
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.Linq;

    internal sealed class Configuration : DbMigrationsConfiguration<WeddingPlanner.Models.ApplicationDbContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = false;
        }

        protected override void Seed(WeddingPlanner.Models.ApplicationDbContext context)
        {
            context.DJs.AddOrUpdate(
            new Models.DJ
            {
                VendorType = "DJ",
                Name = "Barry Burton",
                Email = "musicBear@gmail.com",
                Phone = "111-333-4567",
                LGBTQFriendly = true,
                DoesTravel = false,
                GenrePop = true,
                GenreRB = false,
                GenreRap = true,
                GenreRock = false,
                GenreCountry = false,
                GenreDance = false,
                GenreTechno = true,
                GenreMetal = false,
                GenreInternational = false,
                GenreOther = false,
                Street = "111 Weatherbeak",
                City = "Vernon Hills",
                State = "WI",
                Zip = "53220",
                Country = "United States"
            },
            new Models.DJ
            {
                VendorType = "DJ",
                Name = "Rebecca Chambers",
                Email = "musicBird@gmail.com",
                Phone = "222-333-4567",
                LGBTQFriendly = true,
                DoesTravel = true,
                GenrePop = true,
                GenreRB = true,
                GenreRap = true,
                GenreRock = false,
                GenreCountry = false,
                GenreDance = true,
                GenreTechno = false,
                GenreMetal = false,
                GenreInternational = false,
                GenreOther = false,
                Street = "111 Weatherbeak",
                City = "Vernon Hills",
                State = "WI",
                Zip = "53220",
                Country = "United States"
            },
            new Models.DJ
            {
                VendorType = "DJ",
                Name = "Albert Wesker",
                Email = "musicBruce@gmail.com",
                Phone = "333-333-4567",
                LGBTQFriendly = false,
                DoesTravel = true,
                GenrePop = false,
                GenreRB = true,
                GenreRap = true,
                GenreRock = false,
                GenreCountry = false,
                GenreDance = false,
                GenreTechno = false,
                GenreMetal = false,
                GenreInternational = false,
                GenreOther = true,
                Street = "111 Weatherbeak",
                City = "Vernon Hills",
                State = "WI",
                Zip = "53220",
                Country = "United States"
            },
            new Models.DJ
            {
                VendorType = "DJ",
                Name = "Sara Lass",
                Email = "musicSara@gmail.com",
                Phone = "444-333-4567",
                LGBTQFriendly = false,
                DoesTravel = false,
                GenrePop = true,
                GenreRB = true,
                GenreRap = true,
                GenreRock = false,
                GenreCountry = false,
                GenreDance = true,
                GenreTechno = true,
                GenreMetal = false,
                GenreInternational = true,
                GenreOther = false,
                Street = "111 Weatherbeak",
                City = "Vernon Hills",
                State = "WI",
                Zip = "53220",
                Country = "United States"
            },
            new Models.DJ
            {
                VendorType = "DJ",
                Name = "Yuji Naka",
                Email = "RadioSega@gmail.com",
                Phone = "555-333-4567",
                LGBTQFriendly = true,
                DoesTravel = false,
                GenrePop = true,
                GenreRB = false,
                GenreRap = true,
                GenreRock = false,
                GenreCountry = true,
                GenreDance = false,
                GenreTechno = true,
                GenreMetal = false,
                GenreInternational = true,
                GenreOther = false,
                Street = "111 Weatherbeak",
                City = "Vernon Hills",
                State = "WI",
                Zip = "53220",
                Country = "United States"
            }
            );
            //Photographers
            context.Photographers.AddOrUpdate(
            new Models.Photographer { VendorType = "Photographer", Name = "Burt Biggleson", Email = "Picman@gmail.com", Phone = "111-444-4567", LGBTQFriendly = true, DoesTravel = true, DoesEditing = false, DoesVideo = false, Street = "111 Weatherbeak", City = "Vernon Hills", State = "WI", Zip = "53220", Country = "United States" },
            new Models.Photographer { VendorType = "Photographer", Name = "Lesly Knope", Email = "knope@gmail.com", Phone = "222-444-4567", LGBTQFriendly = true, DoesTravel = true, DoesEditing = true, DoesVideo = true, Street = "111 Weatherbeak", City = "Vernon Hills", State = "WI", Zip = "53220", Country = "United States" },
            new Models.Photographer { VendorType = "Photographer", Name = "Linda Binderson", Email = "LindaB@gmail.com", Phone = "333-444-4567", LGBTQFriendly = true, DoesTravel = true, DoesEditing = false, DoesVideo = true, Street = "111 Weatherbeak", City = "Vernon Hills", State = "WI", Zip = "53220", Country = "United States" },
            new Models.Photographer { VendorType = "Photographer", Name = "Sam Hamson", Email = "bamSam@gmail.com", Phone = "444-444-4567", LGBTQFriendly = false, DoesTravel = true, DoesEditing = false, DoesVideo = true, Street = "111 Weatherbeak", City = "Vernon Hills", State = "WI", Zip = "53220", Country = "United States" },
            new Models.Photographer { VendorType = "Photographer", Name = "Ham Samson", Email = "perfect_ham@gmail.com", Phone = "555-444-4567", LGBTQFriendly = true, DoesTravel = false, DoesEditing = false, DoesVideo = true, Street = "111 Weatherbeak", City = "Vernon Hills", State = "WI", Zip = "53220", Country = "United States" });
            //Caterers
            context.Caterers.AddOrUpdate(
            new Models.Caterer
            {
                VendorType = "Caterer",
                Name = "Best Caterer",
                Email = "bestcaterer@gmail.com",
                Phone = "414-111-0011",
                LGBTQFriendly = true,
                ServesVegan = true,
                FoodAllergyOptions = true,
                PerGuestEstimateLow = 50,
                PerGuestEstimateHigh = 100,
                FoodIndian = true,
                FoodItalian = false,
                FoodChinese = true,
                FoodMediterranean = true,
                FoodMexican = false,
                FoodFrench = false,
                FoodAmerican = false,
                FoodOther = false,
                Street = "111 Weatherbeak",
                City = "Vernon Hills",
                State = "WI",
                Zip = "53220",
                Country = "United States"
            },
            new Models.Caterer
            {
                VendorType = "Caterer",
                Name = "AllFoods Caterer",
                Email = "allfoods@gmail.com",
                Phone = "414-111-0022",
                LGBTQFriendly = true,
                ServesVegan = false,
                FoodAllergyOptions = true,
                PerGuestEstimateLow = 75,
                PerGuestEstimateHigh = 200,
                FoodIndian = true,
                FoodItalian = true,
                FoodChinese = true,
                FoodMediterranean = true,
                FoodMexican = true,
                FoodFrench = true,
                FoodAmerican = true,
                FoodOther = true,
                Street = "111 Weatherbeak",
                City = "Vernon Hills",
                State = "WI",
                Zip = "53220",
                Country = "United States"
            },
            new Models.Caterer
            {
                VendorType = "Caterer",
                Name = "GourmetFoods Caterer",
                Email = "gourmetfoods@gmail.com",
                Phone = "414-111-0033",
                LGBTQFriendly = true,
                ServesVegan = true,
                FoodAllergyOptions = false,
                PerGuestEstimateLow = 90,
                PerGuestEstimateHigh = 250,
                FoodIndian = false,
                FoodItalian = true,
                FoodChinese = false,
                FoodMediterranean = false,
                FoodMexican = true,
                FoodFrench = true,
                FoodAmerican = true,
                FoodOther = false,
                Street = "111 Weatherbeak",
                City = "Vernon Hills",
                State = "WI",
                Zip = "53220",
                Country = "United States"
            },
            new Models.Caterer
            {
                VendorType = "Caterer",
                Name = "Milwaukee Caterers",
                Email = "milwaukeecaterers@gmail.com",
                Phone = "414-111-0044",
                LGBTQFriendly = false,
                ServesVegan = false,
                FoodAllergyOptions = true,
                PerGuestEstimateLow = 50,
                PerGuestEstimateHigh = 150,
                FoodIndian = false,
                FoodItalian = false,
                FoodChinese = true,
                FoodMediterranean = false,
                FoodMexican = true,
                FoodFrench = false,
                FoodAmerican = true,
                FoodOther = true,
                Street = "111 Weatherbeak",
                City = "Vernon Hills",
                State = "WI",
                Zip = "53220",
                Country = "United States"
            },
            new Models.Caterer
            {
                VendorType = "Caterer",
                Name = "Your Favorite Caterer",
                Email = "yourfavoritecaterer@gmail.com",
                Phone = "414-111-0055",
                LGBTQFriendly = true,
                ServesVegan = true,
                FoodAllergyOptions = false,
                PerGuestEstimateLow = 75,
                PerGuestEstimateHigh = 150,
                FoodIndian = true,
                FoodItalian = true,
                FoodChinese = false,
                FoodMediterranean = false,
                FoodMexican = true,
                FoodFrench = true,
                FoodAmerican = true,
                FoodOther = false,
                Street = "111 Weatherbeak",
                City = "Vernon Hills",
                State = "WI",
                Zip = "53220",
                Country = "United States"
            });
            //celebrant
            context.Celebrants.AddOrUpdate(
            new Models.Celebrant
            {
                VendorType = "Celebrant",
                Name = "Henry Zabrowski",
                Email = "lastOnLeft@gmail.com",
                Phone = "666-111-4567",
                ReligionOther = true,
                Buddhism = false,
                Lutheranism = false,
                Catholicism = false,
                NonDenominational = false,
                Islamic = true,
                Hinduism = true,
                Sikhism = true,
                Judaism = true,
                LGBTQFriendly = true,
                DoesTravel = true,
                Street = "111 Weatherbeak",
                City = "Vernon Hills",
                State = "WI",
                Zip = "53220",
                Country = "United States"
            },
            new Models.Celebrant
            {
                VendorType = "Celebrant",
                Name = "Pope Sanchez",
                Email = "lastOnLeft@gmail.com",
                Phone = "666-111-4567",
                LGBTQFriendly = true,
                ReligionOther = true,
                Buddhism = true,
                Lutheranism = true,
                Catholicism = true,
                NonDenominational = true,
                Islamic = false,
                Hinduism = false,
                Sikhism = false,
                Judaism = false,
                DoesTravel = true,
                Street = "111 Weatherbeak",
                City = "Vernon Hills",
                State = "WI",
                Zip = "53220",
                Country = "United States"
            },
            new Models.Celebrant
            {
                VendorType = "Celebrant",
                Name = "Hope Panchez",
                Email = "lastOnLeft@gmail.com",
                Phone = "666-111-4567",
                ReligionOther = true,
                Buddhism = true,
                Lutheranism = true,
                Catholicism = true,
                NonDenominational = true,
                Islamic = true,
                Hinduism = true,
                Sikhism = true,
                Judaism = true,
                LGBTQFriendly = true,
                DoesTravel = true,
                Street = "111 Weatherbeak",
                City = "Vernon Hills",
                State = "WI",
                Zip = "53220",
                Country = "United States"
            },
            new Models.Celebrant
            {
                VendorType = "Celebrant",
                Name = "Chope Manchez",
                Email = "lastOnLeft@gmail.com",
                Phone = "666-111-4567",
                ReligionOther = true,
                Buddhism = false,
                Lutheranism = true,
                Catholicism = false,
                NonDenominational = true,
                Islamic = false,
                Hinduism = true,
                Sikhism = false,
                Judaism = true,
                LGBTQFriendly = true,
                DoesTravel = true,
                Street = "111 Weatherbeak",
                City = "Vernon Hills",
                State = "WI",
                Zip = "53220",
                Country = "United States"
            },
            new Models.Celebrant
            {
                VendorType = "Celebrant",
                Name = "Yuji Naka",
                Email = "lastOnLeft@gmail.com",
                Phone = "666-111-4567",
                ReligionOther = true,
                Buddhism = true,
                Lutheranism = true,
                Catholicism = true,
                NonDenominational = true,
                Islamic = true,
                Hinduism = true,
                Sikhism = true,
                Judaism = true,
                LGBTQFriendly = true,
                DoesTravel = true,
                Street = "111 Weatherbeak",
                City = "Vernon Hills",
                State = "WI",
                Zip = "53220",
                Country = "United States"
            });
            //Venue
            context.Venues.AddOrUpdate(
            new Models.Venue
            {
                VendorType = "Venue",
                Name = "Paradiso",
                Email = "paradiso@gmail.com",
                Phone = "414 222 1111",
                LGBTQFriendly = true,
                KidFriendly = true,
                PetFriendly = false,
                HandicapAccessible = true,
                ReligionOther = true,
                Buddhism = true,
                Lutheranism = true,
                Catholicism = true,
                NonDenominational = true,
                Islamic = true,
                Hinduism = true,
                Sikhism = true,
                Judaism = true,
                ServesCohabitants = true,
                Ceremony = true,
                Reception = true,
                ProvidesLodging = false,
                AllowsDecor = true,
                ThirdPartyCelebrant = true,
                ThirdPartyCatering = true,
                ThirdPartyDJ = true,
                Caterers = false,
                Street = "111 Weatherbeak",
                City = "Vernon Hills",
                State = "WI",
                Zip = "53220",
                Country = "United States",
            },
            new Models.Venue
            {
                VendorType = "Venue",
                Name = "TajMahal",
                Email = "tajmahal@gmail.com",
                Phone = "414 222 2222",
                LGBTQFriendly = true,
                KidFriendly = true,
                PetFriendly = true,
                HandicapAccessible = true,
                ReligionOther = false,
                Buddhism = false,
                Lutheranism = true,
                Catholicism = true,
                NonDenominational = true,
                Islamic = false,
                Hinduism = false,
                Sikhism = false,
                Judaism = false,
                ServesCohabitants = true,
                Ceremony = false,
                Reception = true,
                ProvidesLodging = false,
                AllowsDecor = true,
                ThirdPartyCelebrant = true,
                ThirdPartyCatering = false,
                ThirdPartyDJ = true,
                Caterers = true,
                Street = "111 Weatherbeak",
                City = "Vernon Hills",
                State = "WI",
                Zip = "53220",
                Country = "United States",
            },
            new Models.Venue
            {
                VendorType = "Venue",
                Name = "Hyatt",
                Email = "hyatt@gmail.com",
                Phone = "414 222 3333",
                LGBTQFriendly = false,
                KidFriendly = false,
                PetFriendly = false,
                HandicapAccessible = true,
                ReligionOther = true,
                Buddhism = true,
                Lutheranism = false,
                Catholicism = false,
                NonDenominational = false,
                Islamic = false,
                Hinduism = true,
                Sikhism = true,
                Judaism = true,
                ServesCohabitants = true,
                Ceremony = true,
                Reception = true,
                ProvidesLodging = false,
                AllowsDecor = true,
                ThirdPartyCelebrant = true,
                ThirdPartyCatering = true,
                ThirdPartyDJ = true,
                Caterers = false,
                Street = "111 Weatherbeak",
                City = "Vernon Hills",
                State = "WI",
                Zip = "53220",
                Country = "United States",
            },
            new Models.Venue
            {
                VendorType = "Venue",
                Name = "Sofitel",
                Email = "sofitel@gmail.com",
                Phone = "414 222 4444",
                LGBTQFriendly = true,
                KidFriendly = true,
                PetFriendly = false,
                HandicapAccessible = false,
                ReligionOther = false,
                Buddhism = true,
                Lutheranism = true,
                Catholicism = true,
                NonDenominational = false,
                Islamic = true,
                Hinduism = true,
                Sikhism = true,
                Judaism = false,
                ServesCohabitants = false,
                Ceremony = true,
                Reception = true,
                ProvidesLodging = true,
                AllowsDecor = false,
                ThirdPartyCelebrant = false,
                ThirdPartyCatering = false,
                ThirdPartyDJ = false,
                Caterers = true,
                Street = "111 Weatherbeak",
                City = "Vernon Hills",
                State = "WI",
                Zip = "53220",
                Country = "United States",
            },
            new Models.Venue
            {
                VendorType = "Venue",
                Name = "Hilton",
                Email = "hilton@gmail.com",
                Phone = "414 222 5555",
                LGBTQFriendly = true,
                KidFriendly = false,
                PetFriendly = false,
                HandicapAccessible = true,
                ReligionOther = true,
                Buddhism = true,
                Lutheranism = true,
                Catholicism = true,
                NonDenominational = false,
                Islamic = true,
                Hinduism = true,
                Sikhism = false,
                Judaism = false,
                ServesCohabitants = true,
                Ceremony = true,
                Reception = true,
                ProvidesLodging = false,
                AllowsDecor = true,
                ThirdPartyCelebrant = true,
                ThirdPartyCatering = true,
                ThirdPartyDJ = true,
                Caterers = false,
                Street = "111 Weatherbeak",
                City = "Vernon Hills",
                State = "WI",
                Zip = "53220",
                Country = "United States",
            });
            //Couple
            context.Couples.AddOrUpdate(
            new Models.Couple
            {
                Partner1FirstName = "Jeff",
                Partner1LastName = "Smith",
                Partner2FirstName = "Nikki",
                Partner2LastName = "Anderson",
                CoupleStreetAddress = "111 Brady St.",
                City = "Milwaukee",
                Zipcode = 53202,
                WeddingBudget = 50000,
                EstimatedTotal = 0,
                CoupleEmail = "jeffnikki@gmail.com",
                CouplePhone = "309 111 2222"
            });
            //wedding pkg
            context.WeddingPackages.AddOrUpdate(
            new Models.WeddingPackage
            {
                ThirdPartyVendors = true,
                LGBTQFriendly = true,
                ServesCohabitants = true,
                KidFriendly = false,
                PetFriendly = false,
                WheelchairAccessible = true,
                FoodAllergyOptions = true,
                Vegan = false,
                FoodIndian = false,
                FoodItalian = true,
                FoodChinese = true,
                FoodMediterranean = true,
                FoodMexican = true,
                FoodFrench = true,
                FoodAmerican = false,
                FoodOther = false,
                GenrePop = false,
                GenreRB = false,
                GenreRap = false,
                GenreRock = false,
                GenreCountry = false,
                GenreDance = false,
                GenreTechno = false,
                GenreMetal = true,
                GenreInternational = false,
                GenreOther = false,
                Judaism = false,
                Sikhism = false,
                Hinduism = false,
                Islamic = false,
                NonDenominational = false,
                Catholicism = false,
                Lutheranism = false,
                Buddhism = false,
                ReligionOther = false
            });
        }
    }
}